name: Update Wiki

description: 'This action updates the wiki with the latest blog posts.'

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
      with:
        repository: 'git@github.com:SAP/SapMachine.wiki.git'
        ref: 'master'
        token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    - name: setup git config
      run: |
        git config user.name "SapMachine Github Actions Bot"
        git config user.email "sapmachine@sap.com"
    - name: Update Wiki
      run: |
        pip3 install feedparser
        python3 scripts/update_blogs.py update
    - run: git push origin master
      working-directory: .
      shell: bash
