// BEGIN  Generated code -- do not edit
// Generated by aarch64-asmtest.py
    Label back, forth;
    __ bind(back);

// ArithOp
    __ add(r27, r12, r24, Assembler::LSR, 5);          // add x27, x12, x24, LSR #5
    __ sub(r8, r30, r16, Assembler::LSR, 51);          // sub x8, x30, x16, LSR #51
    __ adds(r29, r25, r26, Assembler::LSR, 61);        // adds x29, x25, x26, LSR #61
    __ subs(r11, r17, r28, Assembler::LSL, 17);        // subs x11, x17, x28, LSL #17
    __ addw(r9, r4, r24, Assembler::LSL, 16);          // add w9, w4, w24, LSL #16
    __ subw(r29, r17, r22, Assembler::ASR, 9);         // sub w29, w17, w22, ASR #9
    __ addsw(r9, r3, r23, Assembler::LSL, 21);         // adds w9, w3, w23, LSL #21
    __ subsw(r15, r17, r3, Assembler::LSR, 27);        // subs w15, w17, w3, LSR #27
    __ andr(r10, r19, r20, Assembler::LSL, 61);        // and x10, x19, x20, LSL #61
    __ orr(r14, r27, r16, Assembler::LSR, 7);          // orr x14, x27, x16, LSR #7
    __ eor(r25, r29, r17, Assembler::LSL, 11);         // eor x25, x29, x17, LSL #11
    __ ands(r23, r26, r12, Assembler::ASR, 0);         // ands x23, x26, x12, ASR #0
    __ andw(r19, r15, r26, Assembler::LSR, 15);        // and w19, w15, w26, LSR #15
    __ orrw(r23, r10, r22, Assembler::LSL, 12);        // orr w23, w10, w22, LSL #12
    __ eorw(r29, r17, r7, Assembler::LSL, 9);          // eor w29, w17, w7, LSL #9
    __ andsw(r25, r17, r14, Assembler::LSL, 5);        // ands w25, w17, w14, LSL #5
    __ bic(r10, r28, r16, Assembler::LSR, 13);         // bic x10, x28, x16, LSR #13
    __ orn(r9, r17, r9, Assembler::ASR, 15);           // orn x9, x17, x9, ASR #15
    __ eon(r17, r10, r26, Assembler::ASR, 26);         // eon x17, x10, x26, ASR #26
    __ bics(r30, r25, r19, Assembler::ASR, 36);        // bics x30, x25, x19, ASR #36
    __ bicw(r14, r2, r19, Assembler::LSR, 20);         // bic w14, w2, w19, LSR #20
    __ ornw(r17, r7, r9, Assembler::LSL, 12);          // orn w17, w7, w9, LSL #12
    __ eonw(r26, r5, r1, Assembler::ASR, 16);          // eon w26, w5, w1, ASR #16
    __ bicsw(r15, r2, r2, Assembler::ASR, 8);          // bics w15, w2, w2, ASR #8

// AddSubImmOp
    __ addw(r28, r4, 79u);                             // add w28, w4, #79
    __ addsw(r26, r2, 801u);                           // adds w26, w2, #801
    __ subw(r26, r22, 564u);                           // sub w26, w22, #564
    __ subsw(r16, r25, 482u);                          // subs w16, w25, #482
    __ add(r27, r6, 858u);                             // add x27, x6, #858
    __ adds(r17, r8, 922u);                            // adds x17, x8, #922
    __ sub(r15, r21, 731u);                            // sub x15, x21, #731
    __ subs(r2, r10, 236u);                            // subs x2, x10, #236

// LogicalImmOp
    __ andw(r15, r17, 268427264ull);                   // and w15, w17, #0xfffe000
    __ orrw(r7, r0, 7864320ull);                       // orr w7, w0, #0x780000
    __ eorw(r22, r7, 130023424ull);                    // eor w22, w7, #0x7c00000
    __ andsw(r10, r13, 2097120ull);                    // ands w10, w13, #0x1fffe0
    __ andr(r25, r4, 536608768ull);                    // and x25, x4, #0x1ffc0000
    __ orr(r26, r17, 4194300ull);                      // orr x26, x17, #0x3ffffc
    __ eor(r3, r20, 211106232532992ull);               // eor x3, x20, #0xc00000000000
    __ ands(r12, r2, 70368743653376ull);               // ands x12, x2, #0x3ffffff80000

// AbsOp
    __ b(__ pc());                                     // b .
    __ b(back);                                        // b back
    __ b(forth);                                       // b forth
    __ bl(__ pc());                                    // bl .
    __ bl(back);                                       // bl back
    __ bl(forth);                                      // bl forth

// RegAndAbsOp
    __ cbzw(r1, __ pc());                              // cbz w1, .
    __ cbzw(r1, back);                                 // cbz w1, back
    __ cbzw(r1, forth);                                // cbz w1, forth
    __ cbnzw(r19, __ pc());                            // cbnz w19, .
    __ cbnzw(r19, back);                               // cbnz w19, back
    __ cbnzw(r19, forth);                              // cbnz w19, forth
    __ cbz(r0, __ pc());                               // cbz x0, .
    __ cbz(r0, back);                                  // cbz x0, back
    __ cbz(r0, forth);                                 // cbz x0, forth
    __ cbnz(r6, __ pc());                              // cbnz x6, .
    __ cbnz(r6, back);                                 // cbnz x6, back
    __ cbnz(r6, forth);                                // cbnz x6, forth
    __ adr(r30, __ pc());                              // adr x30, .
    __ adr(r30, back);                                 // adr x30, back
    __ adr(r30, forth);                                // adr x30, forth
    __ _adrp(r5, __ pc());                             // adrp x5, .

// RegImmAbsOp
    __ tbz(r22, 3, __ pc());                           // tbz x22, #3, .
    __ tbz(r22, 3, back);                              // tbz x22, #3, back
    __ tbz(r22, 3, forth);                             // tbz x22, #3, forth
    __ tbnz(r15, 6, __ pc());                          // tbnz x15, #6, .
    __ tbnz(r15, 6, back);                             // tbnz x15, #6, back
    __ tbnz(r15, 6, forth);                            // tbnz x15, #6, forth

// MoveWideImmOp
    __ movnw(r23, 4003, 0);                            // movn w23, #4003, lsl 0
    __ movzw(r17, 27893, 0);                           // movz w17, #27893, lsl 0
    __ movkw(r26, 17034, 0);                           // movk w26, #17034, lsl 0
    __ movn(r7, 4716, 32);                             // movn x7, #4716, lsl 32
    __ movz(r11, 28578, 16);                           // movz x11, #28578, lsl 16
    __ movk(r1, 30613, 0);                             // movk x1, #30613, lsl 0

// BitfieldOp
    __ sbfm(r19, r3, 25, 12);                          // sbfm x19, x3, #25, #12
    __ bfmw(r8, r11, 30, 10);                          // bfm w8, w11, #30, #10
    __ ubfmw(r22, r21, 13, 3);                         // ubfm w22, w21, #13, #3
    __ sbfm(r25, r21, 10, 10);                         // sbfm x25, x21, #10, #10
    __ bfm(r10, r16, 16, 7);                           // bfm x10, x16, #16, #7
    __ ubfm(r19, r29, 28, 11);                         // ubfm x19, x29, #28, #11

// ExtractOp
    __ extrw(r0, r15, r21, 26);                        // extr w0, w15, w21, #26
    __ extr(r28, r17, r27, 39);                        // extr x28, x17, x27, #39

// CondBranchOp
    __ br(Assembler::EQ, __ pc());                     // b.EQ .
    __ br(Assembler::EQ, back);                        // b.EQ back
    __ br(Assembler::EQ, forth);                       // b.EQ forth
    __ br(Assembler::NE, __ pc());                     // b.NE .
    __ br(Assembler::NE, back);                        // b.NE back
    __ br(Assembler::NE, forth);                       // b.NE forth
    __ br(Assembler::HS, __ pc());                     // b.HS .
    __ br(Assembler::HS, back);                        // b.HS back
    __ br(Assembler::HS, forth);                       // b.HS forth
    __ br(Assembler::CS, __ pc());                     // b.CS .
    __ br(Assembler::CS, back);                        // b.CS back
    __ br(Assembler::CS, forth);                       // b.CS forth
    __ br(Assembler::LO, __ pc());                     // b.LO .
    __ br(Assembler::LO, back);                        // b.LO back
    __ br(Assembler::LO, forth);                       // b.LO forth
    __ br(Assembler::CC, __ pc());                     // b.CC .
    __ br(Assembler::CC, back);                        // b.CC back
    __ br(Assembler::CC, forth);                       // b.CC forth
    __ br(Assembler::MI, __ pc());                     // b.MI .
    __ br(Assembler::MI, back);                        // b.MI back
    __ br(Assembler::MI, forth);                       // b.MI forth
    __ br(Assembler::PL, __ pc());                     // b.PL .
    __ br(Assembler::PL, back);                        // b.PL back
    __ br(Assembler::PL, forth);                       // b.PL forth
    __ br(Assembler::VS, __ pc());                     // b.VS .
    __ br(Assembler::VS, back);                        // b.VS back
    __ br(Assembler::VS, forth);                       // b.VS forth
    __ br(Assembler::VC, __ pc());                     // b.VC .
    __ br(Assembler::VC, back);                        // b.VC back
    __ br(Assembler::VC, forth);                       // b.VC forth
    __ br(Assembler::HI, __ pc());                     // b.HI .
    __ br(Assembler::HI, back);                        // b.HI back
    __ br(Assembler::HI, forth);                       // b.HI forth
    __ br(Assembler::LS, __ pc());                     // b.LS .
    __ br(Assembler::LS, back);                        // b.LS back
    __ br(Assembler::LS, forth);                       // b.LS forth
    __ br(Assembler::GE, __ pc());                     // b.GE .
    __ br(Assembler::GE, back);                        // b.GE back
    __ br(Assembler::GE, forth);                       // b.GE forth
    __ br(Assembler::LT, __ pc());                     // b.LT .
    __ br(Assembler::LT, back);                        // b.LT back
    __ br(Assembler::LT, forth);                       // b.LT forth
    __ br(Assembler::GT, __ pc());                     // b.GT .
    __ br(Assembler::GT, back);                        // b.GT back
    __ br(Assembler::GT, forth);                       // b.GT forth
    __ br(Assembler::LE, __ pc());                     // b.LE .
    __ br(Assembler::LE, back);                        // b.LE back
    __ br(Assembler::LE, forth);                       // b.LE forth
    __ br(Assembler::AL, __ pc());                     // b.AL .
    __ br(Assembler::AL, back);                        // b.AL back
    __ br(Assembler::AL, forth);                       // b.AL forth
    __ br(Assembler::NV, __ pc());                     // b.NV .
    __ br(Assembler::NV, back);                        // b.NV back
    __ br(Assembler::NV, forth);                       // b.NV forth

// ImmOp
    __ svc(23406);                                     // svc #23406
    __ hvc(25470);                                     // hvc #25470
    __ smc(16445);                                     // smc #16445
    __ brk(10054);                                     // brk #10054
    __ hlt(815);                                       // hlt #815

// Op
    __ nop();                                          // nop
    __ eret();                                         // eret
    __ drps();                                         // drps
    __ isb();                                          // isb

// SystemOp
    __ dsb(Assembler::ISHST);                          // dsb ISHST
    __ dmb(Assembler::SY);                             // dmb SY

// OneRegOp
    __ br(r2);                                         // br x2
    __ blr(r10);                                       // blr x10

// LoadStoreExclusiveOp
    __ stxr(r23, r1, r17);                             // stxr w23, x1, [x17]
    __ stlxr(r8, r4, r7);                              // stlxr w8, x4, [x7]
    __ ldxr(r24, r30);                                 // ldxr x24, [x30]
    __ ldaxr(r15, r11);                                // ldaxr x15, [x11]
    __ stlr(r19, r9);                                  // stlr x19, [x9]
    __ ldar(r21, r11);                                 // ldar x21, [x11]

// LoadStoreExclusiveOp
    __ stxrw(r17, r30, r28);                           // stxr w17, w30, [x28]
    __ stlxrw(r20, r27, r19);                          // stlxr w20, w27, [x19]
    __ ldxrw(r4, r22);                                 // ldxr w4, [x22]
    __ ldaxrw(r9, r12);                                // ldaxr w9, [x12]
    __ stlrw(r23, r13);                                // stlr w23, [x13]
    __ ldarw(r26, r20);                                // ldar w26, [x20]

// LoadStoreExclusiveOp
    __ stxrh(r2, r0, r19);                             // stxrh w2, w0, [x19]
    __ stlxrh(r6, r22, r10);                           // stlxrh w6, w22, [x10]
    __ ldxrh(r5, r7);                                  // ldxrh w5, [x7]
    __ ldaxrh(r7, r20);                                // ldaxrh w7, [x20]
    __ stlrh(r14, r12);                                // stlrh w14, [x12]
    __ ldarh(r22, r28);                                // ldarh w22, [x28]

// LoadStoreExclusiveOp
    __ stxrb(r21, r17, r27);                           // stxrb w21, w17, [x27]
    __ stlxrb(r13, r1, r12);                           // stlxrb w13, w1, [x12]
    __ ldxrb(r27, r22);                                // ldxrb w27, [x22]
    __ ldaxrb(r17, r13);                               // ldaxrb w17, [x13]
    __ stlrb(r24, r21);                                // stlrb w24, [x21]
    __ ldarb(r22, r1);                                 // ldarb w22, [x1]

// LoadStoreExclusiveOp
    __ ldxp(r5, r14, r2);                              // ldxp x5, x14, [x2]
    __ ldaxp(r8, r22, r5);                             // ldaxp x8, x22, [x5]
    __ stxp(r14, r16, r28, r15);                       // stxp w14, x16, x28, [x15]
    __ stlxp(r29, r17, r19, r24);                      // stlxp w29, x17, x19, [x24]

// LoadStoreExclusiveOp
    __ ldxpw(r0, r28, r1);                             // ldxp w0, w28, [x1]
    __ ldaxpw(r15, r10, r9);                           // ldaxp w15, w10, [x9]
    __ stxpw(r26, r14, r1, r25);                       // stxp w26, w14, w1, [x25]
    __ stlxpw(r26, r28, r25, r13);                     // stlxp w26, w28, w25, [x13]

// base_plus_unscaled_offset
// LoadStoreOp
    __ str(r10, Address(r6, 69));                      // str x10, [x6, 69]
    __ strw(r19, Address(r0, -125));                   // str w19, [x0, -125]
    __ strb(r20, Address(r20, -13));                   // strb w20, [x20, -13]
    __ strh(r27, Address(r2, -29));                    // strh w27, [x2, -29]
    __ ldr(r30, Address(r4, -247));                    // ldr x30, [x4, -247]
    __ ldrw(r11, Address(r17, -118));                  // ldr w11, [x17, -118]
    __ ldrb(r4, Address(r27, -21));                    // ldrb w4, [x27, -21]
    __ ldrh(r8, Address(r8, -21));                     // ldrh w8, [x8, -21]
    __ ldrsb(r15, Address(r5, 5));                     // ldrsb x15, [x5, 5]
    __ ldrsh(r26, Address(r23, -58));                  // ldrsh x26, [x23, -58]
    __ ldrshw(r26, Address(r10, -11));                 // ldrsh w26, [x10, -11]
    __ ldrsw(r9, Address(r25, -41));                   // ldrsw x9, [x25, -41]
    __ ldrd(v25, Address(r10, 95));                    // ldr d25, [x10, 95]
    __ ldrs(v17, Address(r2, 63));                     // ldr s17, [x2, 63]
    __ strd(v11, Address(r16, -27));                   // str d11, [x16, -27]
    __ strs(v26, Address(r7, 21));                     // str s26, [x7, 21]

// pre
// LoadStoreOp
    __ str(r8, Address(__ pre(r6, -242)));             // str x8, [x6, -242]!
    __ strw(r17, Address(__ pre(r27, 31)));            // str w17, [x27, 31]!
    __ strb(r30, Address(__ pre(r29, -1)));            // strb w30, [x29, -1]!
    __ strh(r23, Address(__ pre(r24, -1)));            // strh w23, [x24, -1]!
    __ ldr(r9, Address(__ pre(r23, -238)));            // ldr x9, [x23, -238]!
    __ ldrw(r1, Address(__ pre(r9, -112)));            // ldr w1, [x9, -112]!
    __ ldrb(r16, Address(__ pre(r1, -11)));            // ldrb w16, [x1, -11]!
    __ ldrh(r29, Address(__ pre(r20, 2)));             // ldrh w29, [x20, 2]!
    __ ldrsb(r5, Address(__ pre(r9, -8)));             // ldrsb x5, [x9, -8]!
    __ ldrsh(r26, Address(__ pre(r12, -22)));          // ldrsh x26, [x12, -22]!
    __ ldrshw(r13, Address(__ pre(r4, -48)));          // ldrsh w13, [x4, -48]!
    __ ldrsw(r20, Address(__ pre(r14, 55)));           // ldrsw x20, [x14, 55]!
    __ ldrd(v20, Address(__ pre(r12, -205)));          // ldr d20, [x12, -205]!
    __ ldrs(v3, Address(__ pre(r10, 12)));             // ldr s3, [x10, 12]!
    __ strd(v25, Address(__ pre(r28, 102)));           // str d25, [x28, 102]!
    __ strs(v25, Address(__ pre(r27, -53)));           // str s25, [x27, -53]!

// post
// LoadStoreOp
    __ str(r8, Address(__ post(r29, -23)));            // str x8, [x29], -23
    __ strw(r27, Address(__ post(r29, 17)));           // str w27, [x29], 17
    __ strb(r29, Address(__ post(r19, 1)));            // strb w29, [x19], 1
    __ strh(r0, Address(__ post(r26, -11)));           // strh w0, [x26], -11
    __ ldr(r2, Address(__ post(r3, -241)));            // ldr x2, [x3], -241
    __ ldrw(r20, Address(__ post(r29, -39)));          // ldr w20, [x29], -39
    __ ldrb(r23, Address(__ post(r0, 10)));            // ldrb w23, [x0], 10
    __ ldrh(r8, Address(__ post(r4, -41)));            // ldrh w8, [x4], -41
    __ ldrsb(r19, Address(__ post(r2, -11)));          // ldrsb x19, [x2], -11
    __ ldrsh(r16, Address(__ post(r7, -44)));          // ldrsh x16, [x7], -44
    __ ldrshw(r2, Address(__ post(r23, -17)));         // ldrsh w2, [x23], -17
    __ ldrsw(r11, Address(__ post(r2, 12)));           // ldrsw x11, [x2], 12
    __ ldrd(v0, Address(__ post(r7, 70)));             // ldr d0, [x7], 70
    __ ldrs(v2, Address(__ post(r13, -16)));           // ldr s2, [x13], -16
    __ strd(v5, Address(__ post(r30, -199)));          // str d5, [x30], -199
    __ strs(v14, Address(__ post(r24, -65)));          // str s14, [x24], -65

// base_plus_reg
// LoadStoreOp
    __ str(r0, Address(r20, r20, Address::sxtx(3)));   // str x0, [x20, x20, sxtx #3]
    __ strw(r2, Address(r6, r9, Address::sxtx(2)));    // str w2, [x6, x9, sxtx #2]
    __ strb(r28, Address(r21, r15, Address::uxtw(0))); // strb w28, [x21, w15, uxtw #0]
    __ strh(r23, Address(r21, r1, Address::sxtx(0)));  // strh w23, [x21, x1, sxtx #0]
    __ ldr(r25, Address(r8, r11, Address::uxtw(0)));   // ldr x25, [x8, w11, uxtw #0]
    __ ldrw(r13, Address(r8, r9, Address::lsl(0)));    // ldr w13, [x8, x9, lsl #0]
    __ ldrb(r30, Address(r27, r9, Address::uxtw(0)));  // ldrb w30, [x27, w9, uxtw #0]
    __ ldrh(r5, Address(r20, r17, Address::sxtw(0)));  // ldrh w5, [x20, w17, sxtw #0]
    __ ldrsb(r11, Address(r3, r22, Address::lsl(0)));  // ldrsb x11, [x3, x22, lsl #0]
    __ ldrsh(r20, Address(r20, r15, Address::sxtw(1))); // ldrsh x20, [x20, w15, sxtw #1]
    __ ldrshw(r0, Address(r30, r1, Address::uxtw(0))); // ldrsh w0, [x30, w1, uxtw #0]
    __ ldrsw(r11, Address(r11, r15, Address::sxtx(0))); // ldrsw x11, [x11, x15, sxtx #0]
    __ ldrd(v24, Address(r1, r3, Address::lsl(0)));    // ldr d24, [x1, x3, lsl #0]
    __ ldrs(v10, Address(r17, r9, Address::sxtx(0)));  // ldr s10, [x17, x9, sxtx #0]
    __ strd(v6, Address(r13, r20, Address::sxtw(0)));  // str d6, [x13, w20, sxtw #0]
    __ strs(v25, Address(r29, r5, Address::sxtx(0)));  // str s25, [x29, x5, sxtx #0]

// base_plus_scaled_offset
// LoadStoreOp
    __ str(r20, Address(r6, 14552));                   // str x20, [x6, 14552]
    __ strw(r19, Address(r2, 7564));                   // str w19, [x2, 7564]
    __ strb(r20, Address(r2, 1866));                   // strb w20, [x2, 1866]
    __ strh(r8, Address(r22, 3810));                   // strh w8, [x22, 3810]
    __ ldr(r11, Address(r22, 13000));                  // ldr x11, [x22, 13000]
    __ ldrw(r17, Address(r0, 7600));                   // ldr w17, [x0, 7600]
    __ ldrb(r10, Address(r29, 1745));                  // ldrb w10, [x29, 1745]
    __ ldrh(r2, Address(r17, 3252));                   // ldrh w2, [x17, 3252]
    __ ldrsb(r16, Address(r6, 1538));                  // ldrsb x16, [x6, 1538]
    __ ldrsh(r29, Address(r27, 4054));                 // ldrsh x29, [x27, 4054]
    __ ldrshw(r15, Address(r17, 3842));                // ldrsh w15, [x17, 3842]
    __ ldrsw(r28, Address(r14, 6952));                 // ldrsw x28, [x14, 6952]
    __ ldrd(v7, Address(r29, 14648));                  // ldr d7, [x29, 14648]
    __ ldrs(v19, Address(r15, 7656));                  // ldr s19, [x15, 7656]
    __ strd(v7, Address(r17, 15760));                  // str d7, [x17, 15760]
    __ strs(v9, Address(r0, 7492));                    // str s9, [x0, 7492]

// pcrel
// LoadStoreOp
    __ ldr(r12, forth);                                // ldr x12, forth
    __ ldrw(r23, __ pc());                             // ldr w23, .

// LoadStoreOp
    __ prfm(Address(r26, -133));                       // prfm PLDL1KEEP, [x26, -133]

// LoadStoreOp
    __ prfm(__ pc());                                  // prfm PLDL1KEEP, .

// LoadStoreOp
    __ prfm(Address(r4, r28, Address::lsl(0)));        // prfm PLDL1KEEP, [x4, x28, lsl #0]

// LoadStoreOp
    __ prfm(Address(r29, 16136));                      // prfm PLDL1KEEP, [x29, 16136]

// AddSubCarryOp
    __ adcw(r12, r11, r19);                            // adc w12, w11, w19
    __ adcsw(r17, r4, r20);                            // adcs w17, w4, w20
    __ sbcw(r15, r28, r29);                            // sbc w15, w28, w29
    __ sbcsw(r3, r19, r26);                            // sbcs w3, w19, w26
    __ adc(r0, r16, r19);                              // adc x0, x16, x19
    __ adcs(r11, r15, r14);                            // adcs x11, x15, x14
    __ sbc(r9, r0, r30);                               // sbc x9, x0, x30
    __ sbcs(r7, r17, r20);                             // sbcs x7, x17, x20

// AddSubExtendedOp
    __ addw(r5, r21, r28, ext::sxtx, 4);               // add w5, w21, w28, sxtx #4
    __ addsw(r17, r10, r22, ext::sxtb, 1);             // adds w17, w10, w22, sxtb #1
    __ sub(r4, r19, r12, ext::sxth, 2);                // sub x4, x19, x12, sxth #2
    __ subsw(r25, r9, r12, ext::uxtx, 1);              // subs w25, w9, w12, uxtx #1
    __ add(r1, r10, r23, ext::sxth, 2);                // add x1, x10, x23, sxth #2
    __ adds(r27, r14, r21, ext::sxtb, 2);              // adds x27, x14, x21, sxtb #2
    __ sub(r11, r21, r5, ext::uxtb, 3);                // sub x11, x21, x5, uxtb #3
    __ subs(r11, r17, r17, ext::uxtw, 1);              // subs x11, x17, x17, uxtw #1

// ConditionalCompareOp
    __ ccmnw(r11, r0, 0u, Assembler::NE);              // ccmn w11, w0, #0, NE
    __ ccmpw(r7, r1, 10u, Assembler::PL);              // ccmp w7, w1, #10, PL
    __ ccmn(r2, r26, 13u, Assembler::LS);              // ccmn x2, x26, #13, LS
    __ ccmp(r4, r28, 13u, Assembler::GT);              // ccmp x4, x28, #13, GT

// ConditionalCompareImmedOp
    __ ccmnw(r4, 11, 9, Assembler::LS);                // ccmn w4, #11, #9, LS
    __ ccmpw(r20, 24, 13, Assembler::HI);              // ccmp w20, #24, #13, HI
    __ ccmn(r0, 29, 8, Assembler::LT);                 // ccmn x0, #29, #8, LT
    __ ccmp(r24, 26, 3, Assembler::NE);                // ccmp x24, #26, #3, NE

// ConditionalSelectOp
    __ cselw(r30, r12, r5, Assembler::EQ);             // csel w30, w12, w5, EQ
    __ csincw(r16, r4, r19, Assembler::LO);            // csinc w16, w4, w19, LO
    __ csinvw(r2, r10, r7, Assembler::CC);             // csinv w2, w10, w7, CC
    __ csnegw(r7, r30, r0, Assembler::CC);             // csneg w7, w30, w0, CC
    __ csel(r23, r25, r26, Assembler::CC);             // csel x23, x25, x26, CC
    __ csinc(r22, r2, r13, Assembler::CS);             // csinc x22, x2, x13, CS
    __ csinv(r19, r20, r14, Assembler::LO);            // csinv x19, x20, x14, LO
    __ csneg(r19, r19, r1, Assembler::VS);             // csneg x19, x19, x1, VS

// TwoRegOp
    __ rbitw(r10, r25);                                // rbit w10, w25
    __ rev16w(r23, r23);                               // rev16 w23, w23
    __ revw(r12, r0);                                  // rev w12, w0
    __ clzw(r20, r29);                                 // clz w20, w29
    __ clsw(r28, r1);                                  // cls w28, w1
    __ rbit(r15, r2);                                  // rbit x15, x2
    __ rev16(r11, r9);                                 // rev16 x11, x9
    __ rev32(r21, r4);                                 // rev32 x21, x4
    __ rev(r14, r7);                                   // rev x14, x7
    __ clz(r16, r11);                                  // clz x16, x11
    __ cls(r5, r23);                                   // cls x5, x23

// ThreeRegOp
    __ udivw(r24, r12, r10);                           // udiv w24, w12, w10
    __ sdivw(r8, r25, r15);                            // sdiv w8, w25, w15
    __ lslvw(r30, r12, r0);                            // lslv w30, w12, w0
    __ lsrvw(r9, r16, r28);                            // lsrv w9, w16, w28
    __ asrvw(r9, r17, r15);                            // asrv w9, w17, w15
    __ rorvw(r1, r24, r17);                            // rorv w1, w24, w17
    __ udiv(r17, r17, r8);                             // udiv x17, x17, x8
    __ sdiv(r29, r21, r1);                             // sdiv x29, x21, x1
    __ lslv(r14, r12, r23);                            // lslv x14, x12, x23
    __ lsrv(r3, r12, r11);                             // lsrv x3, x12, x11
    __ asrv(r15, r1, r0);                              // asrv x15, x1, x0
    __ rorv(r8, r23, r1);                              // rorv x8, x23, x1
    __ umulh(r8, r21, r21);                            // umulh x8, x21, x21
    __ smulh(r17, r22, r24);                           // smulh x17, x22, x24

// FourRegMulOp
    __ maddw(r29, r9, r21, r24);                       // madd w29, w9, w21, w24
    __ msubw(r6, r24, r16, r16);                       // msub w6, w24, w16, w16
    __ madd(r10, r12, r26, r8);                        // madd x10, x12, x26, x8
    __ msub(r6, r3, r17, r10);                         // msub x6, x3, x17, x10
    __ smaddl(r25, r30, r30, r29);                     // smaddl x25, w30, w30, x29
    __ smsubl(r7, r17, r21, r23);                      // smsubl x7, w17, w21, x23
    __ umaddl(r17, r21, r28, r11);                     // umaddl x17, w21, w28, x11
    __ umsubl(r5, r29, r27, r28);                      // umsubl x5, w29, w27, x28

// ThreeRegFloatOp
    __ fabds(v4, v10, v27);                            // fabd s4, s10, s27
    __ fmuls(v23, v26, v0);                            // fmul s23, s26, s0
    __ fdivs(v17, v26, v1);                            // fdiv s17, s26, s1
    __ fadds(v17, v4, v30);                            // fadd s17, s4, s30
    __ fsubs(v11, v11, v9);                            // fsub s11, s11, s9
    __ fabdd(v20, v9, v10);                            // fabd d20, d9, d10
    __ fmuld(v15, v25, v12);                           // fmul d15, d25, d12
    __ fdivd(v19, v13, v5);                            // fdiv d19, d13, d5
    __ faddd(v0, v25, v4);                             // fadd d0, d25, d4
    __ fsubd(v17, v1, v14);                            // fsub d17, d1, d14

// FourRegFloatOp
    __ fmadds(v4, v10, v29, v0);                       // fmadd s4, s10, s29, s0
    __ fmsubs(v30, v23, v15, v29);                     // fmsub s30, s23, s15, s29
    __ fnmadds(v30, v21, v26, v21);                    // fnmadd s30, s21, s26, s21
    __ fnmadds(v24, v8, v23, v19);                     // fnmadd s24, s8, s23, s19
    __ fmaddd(v6, v2, v17, v29);                       // fmadd d6, d2, d17, d29
    __ fmsubd(v13, v8, v30, v26);                      // fmsub d13, d8, d30, d26
    __ fnmaddd(v5, v16, v5, v2);                       // fnmadd d5, d16, d5, d2
    __ fnmaddd(v21, v20, v5, v17);                     // fnmadd d21, d20, d5, d17

// TwoRegFloatOp
    __ fmovs(v3, v30);                                 // fmov s3, s30
    __ fabss(v16, v20);                                // fabs s16, s20
    __ fnegs(v25, v17);                                // fneg s25, s17
    __ fsqrts(v19, v12);                               // fsqrt s19, s12
    __ fcvts(v24, v13);                                // fcvt d24, s13
    __ fmovd(v8, v9);                                  // fmov d8, d9
    __ fabsd(v9, v0);                                  // fabs d9, d0
    __ fnegd(v13, v24);                                // fneg d13, d24
    __ fsqrtd(v26, v22);                               // fsqrt d26, d22
    __ fcvtd(v8, v30);                                 // fcvt s8, d30

// FloatConvertOp
    __ fcvtzsw(r8, v17);                               // fcvtzs w8, s17
    __ fcvtzs(r16, v17);                               // fcvtzs x16, s17
    __ fcvtzdw(r10, v10);                              // fcvtzs w10, d10
    __ fcvtzd(r6, v22);                                // fcvtzs x6, d22
    __ scvtfws(v25, r13);                              // scvtf s25, w13
    __ scvtfs(v25, r4);                                // scvtf s25, x4
    __ scvtfwd(v27, r0);                               // scvtf d27, w0
    __ scvtfd(v24, r16);                               // scvtf d24, x16
    __ fmovs(r4, v25);                                 // fmov w4, s25
    __ fmovd(r21, v22);                                // fmov x21, d22
    __ fmovs(v29, r25);                                // fmov s29, w25
    __ fmovd(v17, r12);                                // fmov d17, x12

// TwoRegFloatOp
    __ fcmps(v11, v14);                                // fcmp s11, s14
    __ fcmpd(v30, v1);                                 // fcmp d30, d1
    __ fcmps(v17, 0.0);                                // fcmp s17, #0.0
    __ fcmpd(v29, 0.0);                                // fcmp d29, #0.0

// LoadStorePairOp
    __ stpw(r20, r19, Address(r25, -48));              // stp w20, w19, [x25, #-48]
    __ ldpw(r11, r16, Address(r0, 128));               // ldp w11, w16, [x0, #128]
    __ ldpsw(r11, r21, Address(r20, -176));            // ldpsw x11, x21, [x20, #-176]
    __ stp(r15, r0, Address(r23, 96));                 // stp x15, x0, [x23, #96]
    __ ldp(r7, r8, Address(r28, 112));                 // ldp x7, x8, [x28, #112]

// LoadStorePairOp
    __ stpw(r30, r24, Address(__ pre(r13, -176)));     // stp w30, w24, [x13, #-176]!
    __ ldpw(r24, r23, Address(__ pre(r14, -224)));     // ldp w24, w23, [x14, #-224]!
    __ ldpsw(r23, r3, Address(__ pre(r6, 0)));         // ldpsw x23, x3, [x6, #0]!
    __ stp(r14, r29, Address(__ pre(r13, -176)));      // stp x14, x29, [x13, #-176]!
    __ ldp(r8, r13, Address(__ pre(r29, 64)));         // ldp x8, x13, [x29, #64]!

// LoadStorePairOp
    __ stpw(r24, r11, Address(__ post(r10, 128)));     // stp w24, w11, [x10], #128
    __ ldpw(r0, r25, Address(__ post(r8, -224)));      // ldp w0, w25, [x8], #-224
    __ ldpsw(r13, r25, Address(__ post(r21, -160)));   // ldpsw x13, x25, [x21], #-160
    __ stp(r21, r12, Address(__ post(r29, 64)));       // stp x21, x12, [x29], #64
    __ ldp(r27, r19, Address(__ post(r4, -240)));      // ldp x27, x19, [x4], #-240

// LoadStorePairOp
    __ stnpw(r22, r8, Address(r10, 32));               // stnp w22, w8, [x10, #32]
    __ ldnpw(r16, r4, Address(r29, -256));             // ldnp w16, w4, [x29, #-256]
    __ stnp(r2, r17, Address(r27, -240));              // stnp x2, x17, [x27, #-240]
    __ ldnp(r6, r23, Address(r2, -80));                // ldnp x6, x23, [x2, #-80]

// LdStNEONOp
    __ ld1(v28, __ T8B, Address(r3));                  // ld1 {v28.8B}, [x3]
    __ ld1(v27, v28, __ T16B, Address(__ post(r4, 32))); // ld1 {v27.16B, v28.16B}, [x4], 32
    __ ld1(v26, v27, v28, __ T1D, Address(__ post(r9, r16))); // ld1 {v26.1D, v27.1D, v28.1D}, [x9], x16
    __ ld1(v2, v3, v4, v5, __ T8H, Address(__ post(r17, 64))); // ld1 {v2.8H, v3.8H, v4.8H, v5.8H}, [x17], 64
    __ ld1r(v29, __ T8B, Address(r17));                // ld1r {v29.8B}, [x17]
    __ ld1r(v26, __ T4S, Address(__ post(r4, 4)));     // ld1r {v26.4S}, [x4], 4
    __ ld1r(v22, __ T1D, Address(__ post(r30, r2)));   // ld1r {v22.1D}, [x30], x2
    __ ld2(v0, v1, __ T2D, Address(r10));              // ld2 {v0.2D, v1.2D}, [x10]
    __ ld2(v26, v27, __ T4H, Address(__ post(r26, 16))); // ld2 {v26.4H, v27.4H}, [x26], 16
    __ ld2r(v23, v24, __ T16B, Address(r12));          // ld2r {v23.16B, v24.16B}, [x12]
    __ ld2r(v25, v26, __ T2S, Address(__ post(r4, 8))); // ld2r {v25.2S, v26.2S}, [x4], 8
    __ ld2r(v1, v2, __ T2D, Address(__ post(r12, r29))); // ld2r {v1.2D, v2.2D}, [x12], x29
    __ ld3(v5, v6, v7, __ T4S, Address(__ post(r14, r11))); // ld3 {v5.4S, v6.4S, v7.4S}, [x14], x11
    __ ld3(v0, v1, v2, __ T2S, Address(r0));           // ld3 {v0.2S, v1.2S, v2.2S}, [x0]
    __ ld3r(v25, v26, v27, __ T8H, Address(r11));      // ld3r {v25.8H, v26.8H, v27.8H}, [x11]
    __ ld3r(v0, v1, v2, __ T4S, Address(__ post(r17, 12))); // ld3r {v0.4S, v1.4S, v2.4S}, [x17], 12
    __ ld3r(v4, v5, v6, __ T1D, Address(__ post(r20, r16))); // ld3r {v4.1D, v5.1D, v6.1D}, [x20], x16
    __ ld4(v30, v31, v0, v1, __ T8H, Address(__ post(r29, 64))); // ld4 {v30.8H, v31.8H, v0.8H, v1.8H}, [x29], 64
    __ ld4(v15, v16, v17, v18, __ T8B, Address(__ post(r17, r22))); // ld4 {v15.8B, v16.8B, v17.8B, v18.8B}, [x17], x22
    __ ld4r(v10, v11, v12, v13, __ T8B, Address(r30)); // ld4r {v10.8B, v11.8B, v12.8B, v13.8B}, [x30]
    __ ld4r(v28, v29, v30, v31, __ T4H, Address(__ post(r5, 8))); // ld4r {v28.4H, v29.4H, v30.4H, v31.4H}, [x5], 8
    __ ld4r(v4, v5, v6, v7, __ T2S, Address(__ post(r17, r4))); // ld4r {v4.2S, v5.2S, v6.2S, v7.2S}, [x17], x4

// NEONReduceInstruction
    __ addv(v0, __ T8B, v1);                           // addv b0, v1.8B
    __ addv(v0, __ T16B, v1);                          // addv b0, v1.16B
    __ addv(v26, __ T4H, v27);                         // addv h26, v27.4H
    __ addv(v10, __ T8H, v11);                         // addv h10, v11.8H
    __ addv(v16, __ T4S, v17);                         // addv s16, v17.4S
    __ smaxv(v0, __ T8B, v1);                          // smaxv b0, v1.8B
    __ smaxv(v1, __ T16B, v2);                         // smaxv b1, v2.16B
    __ smaxv(v1, __ T4H, v2);                          // smaxv h1, v2.4H
    __ smaxv(v24, __ T8H, v25);                        // smaxv h24, v25.8H
    __ smaxv(v29, __ T4S, v30);                        // smaxv s29, v30.4S
    __ fmaxv(v3, __ T4S, v4);                          // fmaxv s3, v4.4S
    __ sminv(v17, __ T8B, v18);                        // sminv b17, v18.8B
    __ uminv(v19, __ T8B, v20);                        // uminv b19, v20.8B
    __ sminv(v4, __ T16B, v5);                         // sminv b4, v5.16B
    __ uminv(v24, __ T16B, v25);                       // uminv b24, v25.16B
    __ sminv(v4, __ T4H, v5);                          // sminv h4, v5.4H
    __ uminv(v21, __ T4H, v22);                        // uminv h21, v22.4H
    __ sminv(v25, __ T8H, v26);                        // sminv h25, v26.8H
    __ uminv(v12, __ T8H, v13);                        // uminv h12, v13.8H
    __ sminv(v25, __ T4S, v26);                        // sminv s25, v26.4S
    __ uminv(v0, __ T4S, v1);                          // uminv s0, v1.4S
    __ fminv(v13, __ T4S, v14);                        // fminv s13, v14.4S
    __ fmaxp(v13, v14, __ S);                          // fmaxp s13, v14.2S
    __ fmaxp(v17, v18, __ D);                          // fmaxp d17, v18.2D
    __ fminp(v29, v30, __ S);                          // fminp s29, v30.2S
    __ fminp(v21, v22, __ D);                          // fminp d21, v22.2D

// TwoRegNEONOp
    __ absr(v10, __ T8B, v11);                         // abs v10.8B, v11.8B
    __ absr(v22, __ T16B, v23);                        // abs v22.16B, v23.16B
    __ absr(v7, __ T4H, v8);                           // abs v7.4H, v8.4H
    __ absr(v29, __ T8H, v30);                         // abs v29.8H, v30.8H
    __ absr(v4, __ T2S, v5);                           // abs v4.2S, v5.2S
    __ absr(v11, __ T4S, v12);                         // abs v11.4S, v12.4S
    __ absr(v16, __ T2D, v17);                         // abs v16.2D, v17.2D
    __ fabs(v6, __ T2S, v7);                           // fabs v6.2S, v7.2S
    __ fabs(v17, __ T4S, v18);                         // fabs v17.4S, v18.4S
    __ fabs(v12, __ T2D, v13);                         // fabs v12.2D, v13.2D
    __ fneg(v2, __ T2S, v3);                           // fneg v2.2S, v3.2S
    __ fneg(v4, __ T4S, v5);                           // fneg v4.4S, v5.4S
    __ fneg(v13, __ T2D, v14);                         // fneg v13.2D, v14.2D
    __ fsqrt(v17, __ T2S, v18);                        // fsqrt v17.2S, v18.2S
    __ fsqrt(v21, __ T4S, v22);                        // fsqrt v21.4S, v22.4S
    __ fsqrt(v11, __ T2D, v12);                        // fsqrt v11.2D, v12.2D
    __ notr(v30, __ T8B, v31);                         // not v30.8B, v31.8B
    __ notr(v3, __ T16B, v4);                          // not v3.16B, v4.16B

// ThreeRegNEONOp
    __ andr(v13, __ T8B, v14, v15);                    // and v13.8B, v14.8B, v15.8B
    __ andr(v28, __ T16B, v29, v30);                   // and v28.16B, v29.16B, v30.16B
    __ orr(v13, __ T8B, v14, v15);                     // orr v13.8B, v14.8B, v15.8B
    __ orr(v7, __ T16B, v8, v9);                       // orr v7.16B, v8.16B, v9.16B
    __ eor(v15, __ T8B, v16, v17);                     // eor v15.8B, v16.8B, v17.8B
    __ eor(v12, __ T16B, v13, v14);                    // eor v12.16B, v13.16B, v14.16B
    __ addv(v7, __ T8B, v8, v9);                       // add v7.8B, v8.8B, v9.8B
    __ addv(v29, __ T16B, v30, v31);                   // add v29.16B, v30.16B, v31.16B
    __ addv(v12, __ T4H, v13, v14);                    // add v12.4H, v13.4H, v14.4H
    __ addv(v7, __ T8H, v8, v9);                       // add v7.8H, v8.8H, v9.8H
    __ addv(v20, __ T2S, v21, v22);                    // add v20.2S, v21.2S, v22.2S
    __ addv(v15, __ T4S, v16, v17);                    // add v15.4S, v16.4S, v17.4S
    __ addv(v12, __ T2D, v13, v14);                    // add v12.2D, v13.2D, v14.2D
    __ fadd(v29, __ T2S, v30, v31);                    // fadd v29.2S, v30.2S, v31.2S
    __ fadd(v17, __ T4S, v18, v19);                    // fadd v17.4S, v18.4S, v19.4S
    __ fadd(v2, __ T2D, v3, v4);                       // fadd v2.2D, v3.2D, v4.2D
    __ subv(v26, __ T8B, v27, v28);                    // sub v26.8B, v27.8B, v28.8B
    __ subv(v8, __ T16B, v9, v10);                     // sub v8.16B, v9.16B, v10.16B
    __ subv(v8, __ T4H, v9, v10);                      // sub v8.4H, v9.4H, v10.4H
    __ subv(v28, __ T8H, v29, v30);                    // sub v28.8H, v29.8H, v30.8H
    __ subv(v16, __ T2S, v17, v18);                    // sub v16.2S, v17.2S, v18.2S
    __ subv(v11, __ T4S, v12, v13);                    // sub v11.4S, v12.4S, v13.4S
    __ subv(v17, __ T2D, v18, v19);                    // sub v17.2D, v18.2D, v19.2D
    __ fsub(v0, __ T2S, v1, v2);                       // fsub v0.2S, v1.2S, v2.2S
    __ fsub(v19, __ T4S, v20, v21);                    // fsub v19.4S, v20.4S, v21.4S
    __ fsub(v19, __ T2D, v20, v21);                    // fsub v19.2D, v20.2D, v21.2D
    __ mulv(v24, __ T8B, v25, v26);                    // mul v24.8B, v25.8B, v26.8B
    __ mulv(v15, __ T16B, v16, v17);                   // mul v15.16B, v16.16B, v17.16B
    __ mulv(v28, __ T4H, v29, v30);                    // mul v28.4H, v29.4H, v30.4H
    __ mulv(v7, __ T8H, v8, v9);                       // mul v7.8H, v8.8H, v9.8H
    __ mulv(v8, __ T2S, v9, v10);                      // mul v8.2S, v9.2S, v10.2S
    __ mulv(v1, __ T4S, v2, v3);                       // mul v1.4S, v2.4S, v3.4S
    __ fabd(v19, __ T2S, v20, v21);                    // fabd v19.2S, v20.2S, v21.2S
    __ fabd(v10, __ T4S, v11, v12);                    // fabd v10.4S, v11.4S, v12.4S
    __ fabd(v27, __ T2D, v28, v29);                    // fabd v27.2D, v28.2D, v29.2D
    __ fmul(v25, __ T2S, v26, v27);                    // fmul v25.2S, v26.2S, v27.2S
    __ fmul(v12, __ T4S, v13, v14);                    // fmul v12.4S, v13.4S, v14.4S
    __ fmul(v30, __ T2D, v31, v0);                     // fmul v30.2D, v31.2D, v0.2D
    __ mlav(v20, __ T4H, v21, v22);                    // mla v20.4H, v21.4H, v22.4H
    __ mlav(v3, __ T8H, v4, v5);                       // mla v3.8H, v4.8H, v5.8H
    __ mlav(v17, __ T2S, v18, v19);                    // mla v17.2S, v18.2S, v19.2S
    __ mlav(v28, __ T4S, v29, v30);                    // mla v28.4S, v29.4S, v30.4S
    __ fmla(v27, __ T2S, v28, v29);                    // fmla v27.2S, v28.2S, v29.2S
    __ fmla(v1, __ T4S, v2, v3);                       // fmla v1.4S, v2.4S, v3.4S
    __ fmla(v4, __ T2D, v5, v6);                       // fmla v4.2D, v5.2D, v6.2D
    __ mlsv(v22, __ T4H, v23, v24);                    // mls v22.4H, v23.4H, v24.4H
    __ mlsv(v12, __ T8H, v13, v14);                    // mls v12.8H, v13.8H, v14.8H
    __ mlsv(v0, __ T2S, v1, v2);                       // mls v0.2S, v1.2S, v2.2S
    __ mlsv(v24, __ T4S, v25, v26);                    // mls v24.4S, v25.4S, v26.4S
    __ fmls(v13, __ T2S, v14, v15);                    // fmls v13.2S, v14.2S, v15.2S
    __ fmls(v23, __ T4S, v24, v25);                    // fmls v23.4S, v24.4S, v25.4S
    __ fmls(v27, __ T2D, v28, v29);                    // fmls v27.2D, v28.2D, v29.2D
    __ fdiv(v12, __ T2S, v13, v14);                    // fdiv v12.2S, v13.2S, v14.2S
    __ fdiv(v13, __ T4S, v14, v15);                    // fdiv v13.4S, v14.4S, v15.4S
    __ fdiv(v29, __ T2D, v30, v31);                    // fdiv v29.2D, v30.2D, v31.2D
    __ maxv(v3, __ T8B, v4, v5);                       // smax v3.8B, v4.8B, v5.8B
    __ maxv(v22, __ T16B, v23, v24);                   // smax v22.16B, v23.16B, v24.16B
    __ maxv(v14, __ T4H, v15, v16);                    // smax v14.4H, v15.4H, v16.4H
    __ maxv(v19, __ T8H, v20, v21);                    // smax v19.8H, v20.8H, v21.8H
    __ maxv(v14, __ T2S, v15, v16);                    // smax v14.2S, v15.2S, v16.2S
    __ maxv(v5, __ T4S, v6, v7);                       // smax v5.4S, v6.4S, v7.4S
    __ smaxp(v5, __ T8B, v6, v7);                      // smaxp v5.8B, v6.8B, v7.8B
    __ smaxp(v10, __ T16B, v11, v12);                  // smaxp v10.16B, v11.16B, v12.16B
    __ smaxp(v15, __ T4H, v16, v17);                   // smaxp v15.4H, v16.4H, v17.4H
    __ smaxp(v13, __ T8H, v14, v15);                   // smaxp v13.8H, v14.8H, v15.8H
    __ smaxp(v5, __ T2S, v6, v7);                      // smaxp v5.2S, v6.2S, v7.2S
    __ smaxp(v17, __ T4S, v18, v19);                   // smaxp v17.4S, v18.4S, v19.4S
    __ fmax(v29, __ T2S, v30, v31);                    // fmax v29.2S, v30.2S, v31.2S
    __ fmax(v27, __ T4S, v28, v29);                    // fmax v27.4S, v28.4S, v29.4S
    __ fmax(v9, __ T2D, v10, v11);                     // fmax v9.2D, v10.2D, v11.2D
    __ minv(v24, __ T8B, v25, v26);                    // smin v24.8B, v25.8B, v26.8B
    __ minv(v16, __ T16B, v17, v18);                   // smin v16.16B, v17.16B, v18.16B
    __ minv(v3, __ T4H, v4, v5);                       // smin v3.4H, v4.4H, v5.4H
    __ minv(v29, __ T8H, v30, v31);                    // smin v29.8H, v30.8H, v31.8H
    __ minv(v11, __ T2S, v12, v13);                    // smin v11.2S, v12.2S, v13.2S
    __ minv(v11, __ T4S, v12, v13);                    // smin v11.4S, v12.4S, v13.4S
    __ sminp(v4, __ T8B, v5, v6);                      // sminp v4.8B, v5.8B, v6.8B
    __ sminp(v20, __ T16B, v21, v22);                  // sminp v20.16B, v21.16B, v22.16B
    __ sminp(v11, __ T4H, v12, v13);                   // sminp v11.4H, v12.4H, v13.4H
    __ sminp(v24, __ T8H, v25, v26);                   // sminp v24.8H, v25.8H, v26.8H
    __ sminp(v15, __ T2S, v16, v17);                   // sminp v15.2S, v16.2S, v17.2S
    __ sminp(v20, __ T4S, v21, v22);                   // sminp v20.4S, v21.4S, v22.4S
    __ sqdmulh(v16, __ T4H, v17, v18);                 // sqdmulh v16.4H, v17.4H, v18.4H
    __ sqdmulh(v24, __ T8H, v25, v26);                 // sqdmulh v24.8H, v25.8H, v26.8H
    __ sqdmulh(v1, __ T2S, v2, v3);                    // sqdmulh v1.2S, v2.2S, v3.2S
    __ sqdmulh(v6, __ T4S, v7, v8);                    // sqdmulh v6.4S, v7.4S, v8.4S
    __ shsubv(v28, __ T8B, v29, v30);                  // shsub v28.8B, v29.8B, v30.8B
    __ shsubv(v30, __ T16B, v31, v0);                  // shsub v30.16B, v31.16B, v0.16B
    __ shsubv(v8, __ T4H, v9, v10);                    // shsub v8.4H, v9.4H, v10.4H
    __ shsubv(v5, __ T8H, v6, v7);                     // shsub v5.8H, v6.8H, v7.8H
    __ shsubv(v23, __ T2S, v24, v25);                  // shsub v23.2S, v24.2S, v25.2S
    __ shsubv(v17, __ T4S, v18, v19);                  // shsub v17.4S, v18.4S, v19.4S
    __ fmin(v10, __ T2S, v11, v12);                    // fmin v10.2S, v11.2S, v12.2S
    __ fmin(v9, __ T4S, v10, v11);                     // fmin v9.4S, v10.4S, v11.4S
    __ fmin(v12, __ T2D, v13, v14);                    // fmin v12.2D, v13.2D, v14.2D
    __ cmeq(v20, __ T8B, v21, v22);                    // cmeq v20.8B, v21.8B, v22.8B
    __ cmeq(v1, __ T16B, v2, v3);                      // cmeq v1.16B, v2.16B, v3.16B
    __ cmeq(v9, __ T4H, v10, v11);                     // cmeq v9.4H, v10.4H, v11.4H
    __ cmeq(v17, __ T8H, v18, v19);                    // cmeq v17.8H, v18.8H, v19.8H
    __ cmeq(v13, __ T2S, v14, v15);                    // cmeq v13.2S, v14.2S, v15.2S
    __ cmeq(v1, __ T4S, v2, v3);                       // cmeq v1.4S, v2.4S, v3.4S
    __ cmeq(v21, __ T2D, v22, v23);                    // cmeq v21.2D, v22.2D, v23.2D
    __ fcmeq(v13, __ T2S, v14, v15);                   // fcmeq v13.2S, v14.2S, v15.2S
    __ fcmeq(v8, __ T4S, v9, v10);                     // fcmeq v8.4S, v9.4S, v10.4S
    __ fcmeq(v12, __ T2D, v13, v14);                   // fcmeq v12.2D, v13.2D, v14.2D
    __ cmgt(v23, __ T8B, v24, v25);                    // cmgt v23.8B, v24.8B, v25.8B
    __ cmgt(v6, __ T16B, v7, v8);                      // cmgt v6.16B, v7.16B, v8.16B
    __ cmgt(v11, __ T4H, v12, v13);                    // cmgt v11.4H, v12.4H, v13.4H
    __ cmgt(v4, __ T8H, v5, v6);                       // cmgt v4.8H, v5.8H, v6.8H
    __ cmgt(v4, __ T2S, v5, v6);                       // cmgt v4.2S, v5.2S, v6.2S
    __ cmgt(v3, __ T4S, v4, v5);                       // cmgt v3.4S, v4.4S, v5.4S
    __ cmgt(v19, __ T2D, v20, v21);                    // cmgt v19.2D, v20.2D, v21.2D
    __ cmhi(v11, __ T8B, v12, v13);                    // cmhi v11.8B, v12.8B, v13.8B
    __ cmhi(v5, __ T16B, v6, v7);                      // cmhi v5.16B, v6.16B, v7.16B
    __ cmhi(v0, __ T4H, v1, v2);                       // cmhi v0.4H, v1.4H, v2.4H
    __ cmhi(v13, __ T8H, v14, v15);                    // cmhi v13.8H, v14.8H, v15.8H
    __ cmhi(v17, __ T2S, v18, v19);                    // cmhi v17.2S, v18.2S, v19.2S
    __ cmhi(v12, __ T4S, v13, v14);                    // cmhi v12.4S, v13.4S, v14.4S
    __ cmhi(v14, __ T2D, v15, v16);                    // cmhi v14.2D, v15.2D, v16.2D
    __ cmhs(v2, __ T8B, v3, v4);                       // cmhs v2.8B, v3.8B, v4.8B
    __ cmhs(v20, __ T16B, v21, v22);                   // cmhs v20.16B, v21.16B, v22.16B
    __ cmhs(v22, __ T4H, v23, v24);                    // cmhs v22.4H, v23.4H, v24.4H
    __ cmhs(v22, __ T8H, v23, v24);                    // cmhs v22.8H, v23.8H, v24.8H
    __ cmhs(v21, __ T2S, v22, v23);                    // cmhs v21.2S, v22.2S, v23.2S
    __ cmhs(v2, __ T4S, v3, v4);                       // cmhs v2.4S, v3.4S, v4.4S
    __ cmhs(v24, __ T2D, v25, v26);                    // cmhs v24.2D, v25.2D, v26.2D
    __ fcmgt(v13, __ T2S, v14, v15);                   // fcmgt v13.2S, v14.2S, v15.2S
    __ fcmgt(v17, __ T4S, v18, v19);                   // fcmgt v17.4S, v18.4S, v19.4S
    __ fcmgt(v23, __ T2D, v24, v25);                   // fcmgt v23.2D, v24.2D, v25.2D
    __ cmge(v17, __ T8B, v18, v19);                    // cmge v17.8B, v18.8B, v19.8B
    __ cmge(v4, __ T16B, v5, v6);                      // cmge v4.16B, v5.16B, v6.16B
    __ cmge(v5, __ T4H, v6, v7);                       // cmge v5.4H, v6.4H, v7.4H
    __ cmge(v4, __ T8H, v5, v6);                       // cmge v4.8H, v5.8H, v6.8H
    __ cmge(v6, __ T2S, v7, v8);                       // cmge v6.2S, v7.2S, v8.2S
    __ cmge(v5, __ T4S, v6, v7);                       // cmge v5.4S, v6.4S, v7.4S
    __ cmge(v7, __ T2D, v8, v9);                       // cmge v7.2D, v8.2D, v9.2D
    __ fcmge(v0, __ T2S, v1, v2);                      // fcmge v0.2S, v1.2S, v2.2S
    __ fcmge(v16, __ T4S, v17, v18);                   // fcmge v16.4S, v17.4S, v18.4S
    __ fcmge(v4, __ T2D, v5, v6);                      // fcmge v4.2D, v5.2D, v6.2D

// SpecialCases
    __ ccmn(zr, zr, 3u, Assembler::LE);                // ccmn xzr, xzr, #3, LE
    __ ccmnw(zr, zr, 5u, Assembler::EQ);               // ccmn wzr, wzr, #5, EQ
    __ ccmp(zr, 1, 4u, Assembler::NE);                 // ccmp xzr, 1, #4, NE
    __ ccmpw(zr, 2, 2, Assembler::GT);                 // ccmp wzr, 2, #2, GT
    __ extr(zr, zr, zr, 0);                            // extr xzr, xzr, xzr, 0
    __ stlxp(r0, zr, zr, sp);                          // stlxp w0, xzr, xzr, [sp]
    __ stlxpw(r2, zr, zr, r3);                         // stlxp w2, wzr, wzr, [x3]
    __ stxp(r4, zr, zr, r5);                           // stxp w4, xzr, xzr, [x5]
    __ stxpw(r6, zr, zr, sp);                          // stxp w6, wzr, wzr, [sp]
    __ dup(v0, __ T16B, zr);                           // dup v0.16b, wzr
    __ mov(v1, __ T1D, 0, zr);                         // mov v1.d[0], xzr
    __ mov(v1, __ T2S, 1, zr);                         // mov v1.s[1], wzr
    __ mov(v1, __ T4H, 2, zr);                         // mov v1.h[2], wzr
    __ mov(v1, __ T8B, 3, zr);                         // mov v1.b[3], wzr
    __ smov(r0, v1, __ S, 0);                          // smov x0, v1.s[0]
    __ smov(r0, v1, __ H, 1);                          // smov x0, v1.h[1]
    __ smov(r0, v1, __ B, 2);                          // smov x0, v1.b[2]
    __ umov(r0, v1, __ D, 0);                          // umov x0, v1.d[0]
    __ umov(r0, v1, __ S, 1);                          // umov w0, v1.s[1]
    __ umov(r0, v1, __ H, 2);                          // umov w0, v1.h[2]
    __ umov(r0, v1, __ B, 3);                          // umov w0, v1.b[3]
    __ ld1(v31, v0, __ T2D, Address(__ post(r1, r0))); // ld1 {v31.2d, v0.2d}, [x1], x0
    __ sve_cpy(z0, __ S, p0, v1);                      // mov z0.s, p0/m, s1
    __ sve_inc(r0, __ S);                              // incw x0
    __ sve_dec(r1, __ H);                              // dech x1
    __ sve_lsl(z0, __ B, z1, 7);                       // lsl z0.b, z1.b, #7
    __ sve_lsl(z21, __ H, z1, 15);                     // lsl z21.h, z1.h, #15
    __ sve_lsl(z0, __ S, z1, 31);                      // lsl z0.s, z1.s, #31
    __ sve_lsl(z0, __ D, z1, 63);                      // lsl z0.d, z1.d, #63
    __ sve_lsr(z0, __ B, z1, 7);                       // lsr z0.b, z1.b, #7
    __ sve_asr(z0, __ H, z11, 15);                     // asr z0.h, z11.h, #15
    __ sve_lsr(z30, __ S, z1, 31);                     // lsr z30.s, z1.s, #31
    __ sve_asr(z0, __ D, z1, 63);                      // asr z0.d, z1.d, #63
    __ sve_addvl(sp, r0, 31);                          // addvl sp, x0, #31
    __ sve_addpl(r1, sp, -32);                         // addpl x1, sp, -32
    __ sve_cntp(r8, __ B, p0, p1);                     // cntp x8, p0, p1.b
    __ sve_dup(z0, __ B, 127);                         // dup z0.b, 127
    __ sve_dup(z1, __ H, -128);                        // dup z1.h, -128
    __ sve_dup(z2, __ S, 32512);                       // dup z2.s, 32512
    __ sve_dup(z7, __ D, -32768);                      // dup z7.d, -32768
    __ sve_ld1b(z0, __ B, p0, Address(sp));            // ld1b {z0.b}, p0/z, [sp]
    __ sve_ld1h(z10, __ H, p1, Address(sp, -8));       // ld1h {z10.h}, p1/z, [sp, #-8, MUL VL]
    __ sve_ld1w(z20, __ S, p2, Address(r0, 7));        // ld1w {z20.s}, p2/z, [x0, #7, MUL VL]
    __ sve_ld1b(z30, __ B, p3, Address(sp, r8));       // ld1b {z30.b}, p3/z, [sp, x8]
    __ sve_ld1w(z0, __ S, p4, Address(sp, r28));       // ld1w {z0.s}, p4/z, [sp, x28, LSL #2]
    __ sve_ld1d(z11, __ D, p5, Address(r0, r1));       // ld1d {z11.d}, p5/z, [x0, x1, LSL #3]
    __ sve_st1b(z22, __ B, p6, Address(sp));           // st1b {z22.b}, p6, [sp]
    __ sve_st1b(z31, __ B, p7, Address(sp, -8));       // st1b {z31.b}, p7, [sp, #-8, MUL VL]
    __ sve_st1w(z0, __ S, p1, Address(r0, 7));         // st1w {z0.s}, p1, [x0, #7, MUL VL]
    __ sve_st1b(z0, __ B, p2, Address(sp, r1));        // st1b {z0.b}, p2, [sp, x1]
    __ sve_st1h(z0, __ H, p3, Address(sp, r8));        // st1h {z0.h}, p3, [sp, x8, LSL #1]
    __ sve_st1d(z0, __ D, p4, Address(r0, r17));       // st1d {z0.d}, p4, [x0, x17, LSL #3]
    __ sve_ldr(z0, Address(sp));                       // ldr z0, [sp]
    __ sve_ldr(z31, Address(sp, -256));                // ldr z31, [sp, #-256, MUL VL]
    __ sve_str(z8, Address(r8, 255));                  // str z8, [x8, #255, MUL VL]

// FloatImmediateOp
    __ fmovd(v0, 2.0);                                 // fmov d0, #2.0
    __ fmovd(v0, 2.125);                               // fmov d0, #2.125
    __ fmovd(v0, 4.0);                                 // fmov d0, #4.0
    __ fmovd(v0, 4.25);                                // fmov d0, #4.25
    __ fmovd(v0, 8.0);                                 // fmov d0, #8.0
    __ fmovd(v0, 8.5);                                 // fmov d0, #8.5
    __ fmovd(v0, 16.0);                                // fmov d0, #16.0
    __ fmovd(v0, 17.0);                                // fmov d0, #17.0
    __ fmovd(v0, 0.125);                               // fmov d0, #0.125
    __ fmovd(v0, 0.1328125);                           // fmov d0, #0.1328125
    __ fmovd(v0, 0.25);                                // fmov d0, #0.25
    __ fmovd(v0, 0.265625);                            // fmov d0, #0.265625
    __ fmovd(v0, 0.5);                                 // fmov d0, #0.5
    __ fmovd(v0, 0.53125);                             // fmov d0, #0.53125
    __ fmovd(v0, 1.0);                                 // fmov d0, #1.0
    __ fmovd(v0, 1.0625);                              // fmov d0, #1.0625
    __ fmovd(v0, -2.0);                                // fmov d0, #-2.0
    __ fmovd(v0, -2.125);                              // fmov d0, #-2.125
    __ fmovd(v0, -4.0);                                // fmov d0, #-4.0
    __ fmovd(v0, -4.25);                               // fmov d0, #-4.25
    __ fmovd(v0, -8.0);                                // fmov d0, #-8.0
    __ fmovd(v0, -8.5);                                // fmov d0, #-8.5
    __ fmovd(v0, -16.0);                               // fmov d0, #-16.0
    __ fmovd(v0, -17.0);                               // fmov d0, #-17.0
    __ fmovd(v0, -0.125);                              // fmov d0, #-0.125
    __ fmovd(v0, -0.1328125);                          // fmov d0, #-0.1328125
    __ fmovd(v0, -0.25);                               // fmov d0, #-0.25
    __ fmovd(v0, -0.265625);                           // fmov d0, #-0.265625
    __ fmovd(v0, -0.5);                                // fmov d0, #-0.5
    __ fmovd(v0, -0.53125);                            // fmov d0, #-0.53125
    __ fmovd(v0, -1.0);                                // fmov d0, #-1.0
    __ fmovd(v0, -1.0625);                             // fmov d0, #-1.0625

// LSEOp
    __ swp(Assembler::xword, zr, r22, r15);            // swp xzr, x22, [x15]
    __ ldadd(Assembler::xword, r21, r7, r26);          // ldadd x21, x7, [x26]
    __ ldbic(Assembler::xword, r16, r10, r21);         // ldclr x16, x10, [x21]
    __ ldeor(Assembler::xword, r21, r9, r24);          // ldeor x21, x9, [x24]
    __ ldorr(Assembler::xword, r19, r15, r24);         // ldset x19, x15, [x24]
    __ ldsmin(Assembler::xword, r22, r24, r30);        // ldsmin x22, x24, [x30]
    __ ldsmax(Assembler::xword, r19, r26, r26);        // ldsmax x19, x26, [x26]
    __ ldumin(Assembler::xword, r6, r9, r9);           // ldumin x6, x9, [x9]
    __ ldumax(Assembler::xword, r0, r6, r13);          // ldumax x0, x6, [x13]

// LSEOp
    __ swpa(Assembler::xword, r7, r17, r10);           // swpa x7, x17, [x10]
    __ ldadda(Assembler::xword, r24, r5, r2);          // ldadda x24, x5, [x2]
    __ ldbica(Assembler::xword, r0, r7, r23);          // ldclra x0, x7, [x23]
    __ ldeora(Assembler::xword, r30, r20, r6);         // ldeora x30, x20, [x6]
    __ ldorra(Assembler::xword, r28, r23, r16);        // ldseta x28, x23, [x16]
    __ ldsmina(Assembler::xword, zr, r14, r10);        // ldsmina xzr, x14, [x10]
    __ ldsmaxa(Assembler::xword, r4, r10, r1);         // ldsmaxa x4, x10, [x1]
    __ ldumina(Assembler::xword, r10, r26, r13);       // ldumina x10, x26, [x13]
    __ ldumaxa(Assembler::xword, r28, r25, r16);       // ldumaxa x28, x25, [x16]

// LSEOp
    __ swpal(Assembler::xword, r1, r8, r24);           // swpal x1, x8, [x24]
    __ ldaddal(Assembler::xword, r10, r28, r3);        // ldaddal x10, x28, [x3]
    __ ldbical(Assembler::xword, r24, r5, r25);        // ldclral x24, x5, [x25]
    __ ldeoral(Assembler::xword, r21, r14, r29);       // ldeoral x21, x14, [x29]
    __ ldorral(Assembler::xword, r2, r30, r6);         // ldsetal x2, x30, [x6]
    __ ldsminal(Assembler::xword, r17, zr, r25);       // ldsminal x17, xzr, [x25]
    __ ldsmaxal(Assembler::xword, r30, r16, r11);      // ldsmaxal x30, x16, [x11]
    __ lduminal(Assembler::xword, r14, r23, r10);      // lduminal x14, x23, [x10]
    __ ldumaxal(Assembler::xword, r19, r9, r29);       // ldumaxal x19, x9, [x29]

// LSEOp
    __ swpl(Assembler::xword, r4, r4, r30);            // swpl x4, x4, [x30]
    __ ldaddl(Assembler::xword, r25, r26, r5);         // ldaddl x25, x26, [x5]
    __ ldbicl(Assembler::xword, r16, r30, r14);        // ldclrl x16, x30, [x14]
    __ ldeorl(Assembler::xword, r7, r16, r9);          // ldeorl x7, x16, [x9]
    __ ldorrl(Assembler::xword, r23, r6, r8);          // ldsetl x23, x6, [x8]
    __ ldsminl(Assembler::xword, r3, r8, r12);         // ldsminl x3, x8, [x12]
    __ ldsmaxl(Assembler::xword, r0, r2, r25);         // ldsmaxl x0, x2, [x25]
    __ lduminl(Assembler::xword, zr, r6, r30);         // lduminl xzr, x6, [x30]
    __ ldumaxl(Assembler::xword, r22, r21, r6);        // ldumaxl x22, x21, [x6]

// LSEOp
    __ swp(Assembler::word, r0, r15, r14);             // swp w0, w15, [x14]
    __ ldadd(Assembler::word, zr, r19, r17);           // ldadd wzr, w19, [x17]
    __ ldbic(Assembler::word, r14, r0, sp);            // ldclr w14, w0, [sp]
    __ ldeor(Assembler::word, r22, r21, r5);           // ldeor w22, w21, [x5]
    __ ldorr(Assembler::word, r4, r19, r27);           // ldset w4, w19, [x27]
    __ ldsmin(Assembler::word, r14, r23, r24);         // ldsmin w14, w23, [x24]
    __ ldsmax(Assembler::word, r9, r14, r15);          // ldsmax w9, w14, [x15]
    __ ldumin(Assembler::word, r12, r30, r22);         // ldumin w12, w30, [x22]
    __ ldumax(Assembler::word, r16, r24, r8);          // ldumax w16, w24, [x8]

// LSEOp
    __ swpa(Assembler::word, r7, r25, r22);            // swpa w7, w25, [x22]
    __ ldadda(Assembler::word, r30, r14, r23);         // ldadda w30, w14, [x23]
    __ ldbica(Assembler::word, r22, r27, r17);         // ldclra w22, w27, [x17]
    __ ldeora(Assembler::word, r22, r25, r15);         // ldeora w22, w25, [x15]
    __ ldorra(Assembler::word, r6, r30, r15);          // ldseta w6, w30, [x15]
    __ ldsmina(Assembler::word, r7, r28, r9);          // ldsmina w7, w28, [x9]
    __ ldsmaxa(Assembler::word, r22, r15, r11);        // ldsmaxa w22, w15, [x11]
    __ ldumina(Assembler::word, r21, zr, r14);         // ldumina w21, wzr, [x14]
    __ ldumaxa(Assembler::word, r7, r24, r24);         // ldumaxa w7, w24, [x24]

// LSEOp
    __ swpal(Assembler::word, r29, r29, r14);          // swpal w29, w29, [x14]
    __ ldaddal(Assembler::word, r25, r19, sp);         // ldaddal w25, w19, [sp]
    __ ldbical(Assembler::word, r14, r20, r0);         // ldclral w14, w20, [x0]
    __ ldeoral(Assembler::word, r5, r30, r20);         // ldeoral w5, w30, [x20]
    __ ldorral(Assembler::word, r25, r14, r27);        // ldsetal w25, w14, [x27]
    __ ldsminal(Assembler::word, r3, r2, r26);         // ldsminal w3, w2, [x26]
    __ ldsmaxal(Assembler::word, r5, r16, r12);        // ldsmaxal w5, w16, [x12]
    __ lduminal(Assembler::word, r20, r11, r7);        // lduminal w20, w11, [x7]
    __ ldumaxal(Assembler::word, r11, r23, r1);        // ldumaxal w11, w23, [x1]

// LSEOp
    __ swpl(Assembler::word, r14, r2, r0);             // swpl w14, w2, [x0]
    __ ldaddl(Assembler::word, r24, r0, r8);           // ldaddl w24, w0, [x8]
    __ ldbicl(Assembler::word, r7, r12, r5);           // ldclrl w7, w12, [x5]
    __ ldeorl(Assembler::word, r29, r12, r0);          // ldeorl w29, w12, [x0]
    __ ldorrl(Assembler::word, r26, r4, r11);          // ldsetl w26, w4, [x11]
    __ ldsminl(Assembler::word, r14, r14, r26);        // ldsminl w14, w14, [x26]
    __ ldsmaxl(Assembler::word, r24, r30, r0);         // ldsmaxl w24, w30, [x0]
    __ lduminl(Assembler::word, r27, r13, r24);        // lduminl w27, w13, [x24]
    __ ldumaxl(Assembler::word, r2, r17, r1);          // ldumaxl w2, w17, [x1]

// SHA3SIMDOp
    __ bcax(v17, __ T16B, v11, v22, v11);              // bcax  v17.16B, v11.16B, v22.16B, v11.16B
    __ eor3(v26, __ T16B, v10, v21, v14);              // eor3  v26.16B, v10.16B, v21.16B, v14.16B
    __ rax1(v20, __ T2D, v4, v19);                     // rax1  v20.2D, v4.2D, v19.2D
    __ xar(v16, __ T2D, v2, v8, 13);                   // xar  v16.2D, v2.2D, v8.2D, #13

// SHA512SIMDOp
    __ sha512h(v22, __ T2D, v3, v8);                   // sha512h  q22, q3, v8.2D
    __ sha512h2(v0, __ T2D, v22, v4);                  // sha512h2  q0, q22, v4.2D
    __ sha512su0(v19, __ T2D, v24);                    // sha512su0  v19.2D, v24.2D
    __ sha512su1(v21, __ T2D, v4, v12);                // sha512su1  v21.2D, v4.2D, v12.2D

// SVEVectorOp
    __ sve_add(z6, __ S, z17, z21);                    // add z6.s, z17.s, z21.s
    __ sve_sub(z6, __ B, z13, z16);                    // sub z6.b, z13.b, z16.b
    __ sve_fadd(z17, __ D, z3, z22);                   // fadd z17.d, z3.d, z22.d
    __ sve_fmul(z3, __ D, z16, z28);                   // fmul z3.d, z16.d, z28.d
    __ sve_fsub(z15, __ D, z5, z14);                   // fsub z15.d, z5.d, z14.d
    __ sve_abs(z4, __ D, p6, z8);                      // abs z4.d, p6/m, z8.d
    __ sve_add(z2, __ H, p5, z26);                     // add z2.h, p5/m, z2.h, z26.h
    __ sve_asr(z14, __ D, p3, z11);                    // asr z14.d, p3/m, z14.d, z11.d
    __ sve_cnt(z24, __ D, p6, z0);                     // cnt z24.d, p6/m, z0.d
    __ sve_lsl(z23, __ D, p0, z17);                    // lsl z23.d, p0/m, z23.d, z17.d
    __ sve_lsr(z30, __ D, p7, z7);                     // lsr z30.d, p7/m, z30.d, z7.d
    __ sve_mul(z7, __ D, p4, z15);                     // mul z7.d, p4/m, z7.d, z15.d
    __ sve_neg(z4, __ S, p3, z14);                     // neg z4.s, p3/m, z14.s
    __ sve_not(z11, __ H, p7, z19);                    // not z11.h, p7/m, z19.h
    __ sve_smax(z26, __ S, p1, z6);                    // smax z26.s, p1/m, z26.s, z6.s
    __ sve_smin(z29, __ B, p1, z30);                   // smin z29.b, p1/m, z29.b, z30.b
    __ sve_sub(z4, __ S, p5, z1);                      // sub z4.s, p5/m, z4.s, z1.s
    __ sve_fabs(z27, __ D, p2, z24);                   // fabs z27.d, p2/m, z24.d
    __ sve_fadd(z12, __ D, p3, z13);                   // fadd z12.d, p3/m, z12.d, z13.d
    __ sve_fdiv(z6, __ S, p2, z12);                    // fdiv z6.s, p2/m, z6.s, z12.s
    __ sve_fmax(z25, __ S, p5, z28);                   // fmax z25.s, p5/m, z25.s, z28.s
    __ sve_fmin(z23, __ D, p5, z5);                    // fmin z23.d, p5/m, z23.d, z5.d
    __ sve_fmul(z4, __ S, p7, z28);                    // fmul z4.s, p7/m, z4.s, z28.s
    __ sve_fneg(z19, __ S, p7, z1);                    // fneg z19.s, p7/m, z1.s
    __ sve_frintm(z15, __ S, p5, z17);                 // frintm z15.s, p5/m, z17.s
    __ sve_frintn(z0, __ S, p0, z1);                   // frintn z0.s, p0/m, z1.s
    __ sve_frintp(z7, __ S, p7, z27);                  // frintp z7.s, p7/m, z27.s
    __ sve_fsqrt(z21, __ D, p1, z27);                  // fsqrt z21.d, p1/m, z27.d
    __ sve_fsub(z29, __ D, p4, z28);                   // fsub z29.d, p4/m, z29.d, z28.d
    __ sve_fmla(z15, __ D, p3, z5, z11);               // fmla z15.d, p3/m, z5.d, z11.d
    __ sve_fmls(z22, __ D, p7, z12, z14);              // fmls z22.d, p7/m, z12.d, z14.d
    __ sve_fnmla(z27, __ S, p7, z2, z4);               // fnmla z27.s, p7/m, z2.s, z4.s
    __ sve_fnmls(z24, __ D, p1, z24, z4);              // fnmls z24.d, p1/m, z24.d, z4.d
    __ sve_mla(z30, __ H, p7, z22, z17);               // mla z30.h, p7/m, z22.h, z17.h
    __ sve_mls(z28, __ B, p5, z22, z1);                // mls z28.b, p5/m, z22.b, z1.b
    __ sve_and(z12, z6, z2);                           // and z12.d, z6.d, z2.d
    __ sve_eor(z17, z17, z27);                         // eor z17.d, z17.d, z27.d
    __ sve_orr(z17, z6, z20);                          // orr z17.d, z6.d, z20.d
    __ sve_bic(z30, z21, z4);                          // bic z30.d, z21.d, z4.d

// SVEReductionOp
    __ sve_andv(v9, __ B, p6, z17);                    // andv b9, p6, z17.b
    __ sve_orv(v2, __ B, p7, z24);                     // orv b2, p7, z24.b
    __ sve_eorv(v6, __ S, p6, z19);                    // eorv s6, p6, z19.s
    __ sve_smaxv(v9, __ B, p1, z23);                   // smaxv b9, p1, z23.b
    __ sve_sminv(v24, __ B, p3, z19);                  // sminv b24, p3, z19.b
    __ sve_fminv(v17, __ D, p5, z4);                   // fminv d17, p5, z4.d
    __ sve_fmaxv(v8, __ D, p1, z17);                   // fmaxv d8, p1, z17.d
    __ sve_fadda(v8, __ D, p3, z12);                   // fadda d8, p3, d8, z12.d
    __ sve_uaddv(v23, __ S, p5, z7);                   // uaddv d23, p5, z7.s

    __ bind(forth);

/*
*/

  static const unsigned int insns[] =
  {
    0x8b58159b,     0xcb50cfc8,     0xab5af73d,     0xeb1c462b,
    0x0b184089,     0x4b96263d,     0x2b175469,     0x6b436e2f,
    0x8a14f66a,     0xaa501f6e,     0xca112fb9,     0xea8c0357,
    0x0a5a3df3,     0x2a163157,     0x4a07263d,     0x6a0e1639,
    0x8a70378a,     0xaaa93e29,     0xcaba6951,     0xeab3933e,
    0x0a73504e,     0x2a2930f1,     0x4aa140ba,     0x6aa2204f,
    0x11013c9c,     0x310c845a,     0x5108d2da,     0x71078b30,
    0x910d68db,     0xb10e6911,     0xd10b6eaf,     0xf103b142,
    0x12133a2f,     0x320d0c07,     0x520a10f6,     0x721b3daa,
    0x926e2899,     0xb27e4e3a,     0xd2520683,     0xf26d684c,
    0x14000000,     0x17ffffd7,     0x14000305,     0x94000000,
    0x97ffffd4,     0x94000302,     0x34000001,     0x34fffa21,
    0x34005fe1,     0x35000013,     0x35fff9d3,     0x35005f93,
    0xb4000000,     0xb4fff960,     0xb4005f20,     0xb5000006,
    0xb5fff906,     0xb5005ec6,     0x1000001e,     0x10fff8be,
    0x10005e7e,     0x90000005,     0x36180016,     0x361ff836,
    0x36185df6,     0x3730000f,     0x3737f7cf,     0x37305d8f,
    0x1281f477,     0x528d9eb1,     0x7288515a,     0x92c24d87,
    0xd2adf44b,     0xf28ef2a1,     0x93593073,     0x331e2968,
    0x530d0eb6,     0x934a2ab9,     0xb3501e0a,     0xd35c2fb3,
    0x139569e0,     0x93db9e3c,     0x54000000,     0x54fff5a0,
    0x54005b60,     0x54000001,     0x54fff541,     0x54005b01,
    0x54000002,     0x54fff4e2,     0x54005aa2,     0x54000002,
    0x54fff482,     0x54005a42,     0x54000003,     0x54fff423,
    0x540059e3,     0x54000003,     0x54fff3c3,     0x54005983,
    0x54000004,     0x54fff364,     0x54005924,     0x54000005,
    0x54fff305,     0x540058c5,     0x54000006,     0x54fff2a6,
    0x54005866,     0x54000007,     0x54fff247,     0x54005807,
    0x54000008,     0x54fff1e8,     0x540057a8,     0x54000009,
    0x54fff189,     0x54005749,     0x5400000a,     0x54fff12a,
    0x540056ea,     0x5400000b,     0x54fff0cb,     0x5400568b,
    0x5400000c,     0x54fff06c,     0x5400562c,     0x5400000d,
    0x54fff00d,     0x540055cd,     0x5400000e,     0x54ffefae,
    0x5400556e,     0x5400000f,     0x54ffef4f,     0x5400550f,
    0xd40b6dc1,     0xd40c6fc2,     0xd40807a3,     0xd424e8c0,
    0xd44065e0,     0xd503201f,     0xd69f03e0,     0xd6bf03e0,
    0xd5033fdf,     0xd5033a9f,     0xd5033fbf,     0xd61f0040,
    0xd63f0140,     0xc8177e21,     0xc808fce4,     0xc85f7fd8,
    0xc85ffd6f,     0xc89ffd33,     0xc8dffd75,     0x88117f9e,
    0x8814fe7b,     0x885f7ec4,     0x885ffd89,     0x889ffdb7,
    0x88dffe9a,     0x48027e60,     0x4806fd56,     0x485f7ce5,
    0x485ffe87,     0x489ffd8e,     0x48dfff96,     0x08157f71,
    0x080dfd81,     0x085f7edb,     0x085ffdb1,     0x089ffeb8,
    0x08dffc36,     0xc87f3845,     0xc87fd8a8,     0xc82e71f0,
    0xc83dcf11,     0x887f7020,     0x887fa92f,     0x883a072e,
    0x883ae5bc,     0xf80450ca,     0xb8183013,     0x381f3294,
    0x781e305b,     0xf850909e,     0xb858a22b,     0x385eb364,
    0x785eb108,     0x398014af,     0x789c62fa,     0x78df515a,
    0xb89d7329,     0xfc45f159,     0xbc43f051,     0xfc1e520b,
    0xbc0150fa,     0xf810ecc8,     0xb801ff71,     0x381fffbe,
    0x781fff17,     0xf8512ee9,     0xb8590d21,     0x385f5c30,
    0x78402e9d,     0x389f8d25,     0x789ead9a,     0x78dd0c8d,
    0xb8837dd4,     0xfc533d94,     0xbc40cd43,     0xfc066f99,
    0xbc1cbf79,     0xf81e97a8,     0xb80117bb,     0x3800167d,
    0x781f5740,     0xf850f462,     0xb85d97b4,     0x3840a417,
    0x785d7488,     0x389f5453,     0x789d44f0,     0x78def6e2,
    0xb880c44b,     0xfc4464e0,     0xbc5f05a2,     0xfc1397c5,
    0xbc1bf70e,     0xf834fa80,     0xb829f8c2,     0x382f5abc,
    0x7821eab7,     0xf86b4919,     0xb869690d,     0x38695b7e,
    0x7871ca85,     0x38b6786b,     0x78afda94,     0x78e14bc0,
    0xb8afe96b,     0xfc636838,     0xbc69ea2a,     0xfc34c9a6,
    0xbc25ebb9,     0xf91c6cd4,     0xb91d8c53,     0x391d2854,
    0x791dc6c8,     0xf95966cb,     0xb95db011,     0x395b47aa,
    0x79596a22,     0x399808d0,     0x799faf7d,     0x79de062f,
    0xb99b29dc,     0xfd5c9fa7,     0xbd5de9f3,     0xfd1eca27,
    0xbd1d4409,     0x5800454c,     0x18000017,     0xf897b340,
    0xd8000000,     0xf8bc6880,     0xf99f87a0,     0x1a13016c,
    0x3a140091,     0x5a1d038f,     0x7a1a0263,     0x9a130200,
    0xba0e01eb,     0xda1e0009,     0xfa140227,     0x0b3cf2a5,
    0x2b368551,     0xcb2caa64,     0x6b2c6539,     0x8b37a941,
    0xab3589db,     0xcb250eab,     0xeb31462b,     0x3a401160,
    0x7a4150ea,     0xba5a904d,     0xfa5cc08d,     0x3a4b9889,
    0x7a588a8d,     0xba5db808,     0xfa5a1b03,     0x1a85019e,
    0x1a933490,     0x5a873142,     0x5a8037c7,     0x9a9a3337,
    0x9a8d2456,     0xda8e3293,     0xda816673,     0x5ac0032a,
    0x5ac006f7,     0x5ac0080c,     0x5ac013b4,     0x5ac0143c,
    0xdac0004f,     0xdac0052b,     0xdac00895,     0xdac00cee,
    0xdac01170,     0xdac016e5,     0x1aca0998,     0x1acf0f28,
    0x1ac0219e,     0x1adc2609,     0x1acf2a29,     0x1ad12f01,
    0x9ac80a31,     0x9ac10ebd,     0x9ad7218e,     0x9acb2583,
    0x9ac0282f,     0x9ac12ee8,     0x9bd57ea8,     0x9b587ed1,
    0x1b15613d,     0x1b10c306,     0x9b1a218a,     0x9b11a866,
    0x9b3e77d9,     0x9b35de27,     0x9bbc2eb1,     0x9bbbf3a5,
    0x7ebbd544,     0x1e200b57,     0x1e211b51,     0x1e3e2891,
    0x1e29396b,     0x7eead534,     0x1e6c0b2f,     0x1e6519b3,
    0x1e642b20,     0x1e6e3831,     0x1f1d0144,     0x1f0ff6fe,
    0x1f3a56be,     0x1f374d18,     0x1f517446,     0x1f5ee90d,
    0x1f650a05,     0x1f654695,     0x1e2043c3,     0x1e20c290,
    0x1e214239,     0x1e21c193,     0x1e22c1b8,     0x1e604128,
    0x1e60c009,     0x1e61430d,     0x1e61c2da,     0x1e6243c8,
    0x1e380228,     0x9e380230,     0x1e78014a,     0x9e7802c6,
    0x1e2201b9,     0x9e220099,     0x1e62001b,     0x9e620218,
    0x1e260324,     0x9e6602d5,     0x1e27033d,     0x9e670191,
    0x1e2e2160,     0x1e6123c0,     0x1e202228,     0x1e6023a8,
    0x293a4f34,     0x2950400b,     0x696a568b,     0xa90602ef,
    0xa9472387,     0x29aa61be,     0x29e45dd8,     0x69c00cd7,
    0xa9b575ae,     0xa9c437a8,     0x28902d58,     0x28e46500,
    0x68ec66ad,     0xa88433b5,     0xa8f14c9b,     0x28042156,
    0x286013b0,     0xa8314762,     0xa87b5c46,     0x0c40707c,
    0x4cdfa09b,     0x0cd06d3a,     0x4cdf2622,     0x0d40c23d,
    0x4ddfc89a,     0x0dc2cfd6,     0x4c408d40,     0x0cdf875a,
    0x4d60c197,     0x0dffc899,     0x4dfdcd81,     0x4ccb49c5,
    0x0c404800,     0x4d40e579,     0x4ddfea20,     0x0dd0ee84,
    0x4cdf07be,     0x0cd6022f,     0x0d60e3ca,     0x0dffe4bc,
    0x0de4ea24,     0x0e31b820,     0x4e31b820,     0x0e71bb7a,
    0x4e71b96a,     0x4eb1ba30,     0x0e30a820,     0x4e30a841,
    0x0e70a841,     0x4e70ab38,     0x4eb0abdd,     0x6e30f883,
    0x0e31aa51,     0x2e31aa93,     0x4e31a8a4,     0x6e31ab38,
    0x0e71a8a4,     0x2e71aad5,     0x4e71ab59,     0x6e71a9ac,
    0x4eb1ab59,     0x6eb1a820,     0x6eb0f9cd,     0x7e30f9cd,
    0x7e70fa51,     0x7eb0fbdd,     0x7ef0fad5,     0x0e20b96a,
    0x4e20baf6,     0x0e60b907,     0x4e60bbdd,     0x0ea0b8a4,
    0x4ea0b98b,     0x4ee0ba30,     0x0ea0f8e6,     0x4ea0fa51,
    0x4ee0f9ac,     0x2ea0f862,     0x6ea0f8a4,     0x6ee0f9cd,
    0x2ea1fa51,     0x6ea1fad5,     0x6ee1f98b,     0x2e205bfe,
    0x6e205883,     0x0e2f1dcd,     0x4e3e1fbc,     0x0eaf1dcd,
    0x4ea91d07,     0x2e311e0f,     0x6e2e1dac,     0x0e298507,
    0x4e3f87dd,     0x0e6e85ac,     0x4e698507,     0x0eb686b4,
    0x4eb1860f,     0x4eee85ac,     0x0e3fd7dd,     0x4e33d651,
    0x4e64d462,     0x2e3c877a,     0x6e2a8528,     0x2e6a8528,
    0x6e7e87bc,     0x2eb28630,     0x6ead858b,     0x6ef38651,
    0x0ea2d420,     0x4eb5d693,     0x4ef5d693,     0x0e3a9f38,
    0x4e319e0f,     0x0e7e9fbc,     0x4e699d07,     0x0eaa9d28,
    0x4ea39c41,     0x2eb5d693,     0x6eacd56a,     0x6efdd79b,
    0x2e3bdf59,     0x6e2eddac,     0x6e60dffe,     0x0e7696b4,
    0x4e659483,     0x0eb39651,     0x4ebe97bc,     0x0e3dcf9b,
    0x4e23cc41,     0x4e66cca4,     0x2e7896f6,     0x6e6e95ac,
    0x2ea29420,     0x6eba9738,     0x0eafcdcd,     0x4eb9cf17,
    0x4efdcf9b,     0x2e2efdac,     0x6e2ffdcd,     0x6e7fffdd,
    0x0e256483,     0x4e3866f6,     0x0e7065ee,     0x4e756693,
    0x0eb065ee,     0x4ea764c5,     0x0e27a4c5,     0x4e2ca56a,
    0x0e71a60f,     0x4e6fa5cd,     0x0ea7a4c5,     0x4eb3a651,
    0x0e3ff7dd,     0x4e3df79b,     0x4e6bf549,     0x0e3a6f38,
    0x4e326e30,     0x0e656c83,     0x4e7f6fdd,     0x0ead6d8b,
    0x4ead6d8b,     0x0e26aca4,     0x4e36aeb4,     0x0e6dad8b,
    0x4e7aaf38,     0x0eb1ae0f,     0x4eb6aeb4,     0x0e72b630,
    0x4e7ab738,     0x0ea3b441,     0x4ea8b4e6,     0x0e3e27bc,
    0x4e2027fe,     0x0e6a2528,     0x4e6724c5,     0x0eb92717,
    0x4eb32651,     0x0eacf56a,     0x4eabf549,     0x4eeef5ac,
    0x2e368eb4,     0x6e238c41,     0x2e6b8d49,     0x6e738e51,
    0x2eaf8dcd,     0x6ea38c41,     0x6ef78ed5,     0x0e2fe5cd,
    0x4e2ae528,     0x4e6ee5ac,     0x0e393717,     0x4e2834e6,
    0x0e6d358b,     0x4e6634a4,     0x0ea634a4,     0x4ea53483,
    0x4ef53693,     0x2e2d358b,     0x6e2734c5,     0x2e623420,
    0x6e6f35cd,     0x2eb33651,     0x6eae35ac,     0x6ef035ee,
    0x2e243c62,     0x6e363eb4,     0x2e783ef6,     0x6e783ef6,
    0x2eb73ed5,     0x6ea43c62,     0x6efa3f38,     0x2eafe5cd,
    0x6eb3e651,     0x6ef9e717,     0x0e333e51,     0x4e263ca4,
    0x0e673cc5,     0x4e663ca4,     0x0ea83ce6,     0x4ea73cc5,
    0x4ee93d07,     0x2e22e420,     0x6e32e630,     0x6e66e4a4,
    0xba5fd3e3,     0x3a5f03e5,     0xfa411be4,     0x7a42cbe2,
    0x93df03ff,     0xc820ffff,     0x8822fc7f,     0xc8247cbf,
    0x88267fff,     0x4e010fe0,     0x4e081fe1,     0x4e0c1fe1,
    0x4e0a1fe1,     0x4e071fe1,     0x4e042c20,     0x4e062c20,
    0x4e052c20,     0x4e083c20,     0x0e0c3c20,     0x0e0a3c20,
    0x0e073c20,     0x4cc0ac3f,     0x05a08020,     0x04b0e3e0,
    0x0470e7e1,     0x042f9c20,     0x043f9c35,     0x047f9c20,
    0x04ff9c20,     0x04299420,     0x04319160,     0x0461943e,
    0x04a19020,     0x042053ff,     0x047f5401,     0x25208028,
    0x2538cfe0,     0x2578d001,     0x25b8efe2,     0x25f8f007,
    0xa400a3e0,     0xa4a8a7ea,     0xa547a814,     0xa4084ffe,
    0xa55c53e0,     0xa5e1540b,     0xe400fbf6,     0xe408ffff,
    0xe547e400,     0xe4014be0,     0xe4a84fe0,     0xe5f15000,
    0x858043e0,     0x85a043ff,     0xe59f5d08,     0x1e601000,
    0x1e603000,     0x1e621000,     0x1e623000,     0x1e641000,
    0x1e643000,     0x1e661000,     0x1e663000,     0x1e681000,
    0x1e683000,     0x1e6a1000,     0x1e6a3000,     0x1e6c1000,
    0x1e6c3000,     0x1e6e1000,     0x1e6e3000,     0x1e701000,
    0x1e703000,     0x1e721000,     0x1e723000,     0x1e741000,
    0x1e743000,     0x1e761000,     0x1e763000,     0x1e781000,
    0x1e783000,     0x1e7a1000,     0x1e7a3000,     0x1e7c1000,
    0x1e7c3000,     0x1e7e1000,     0x1e7e3000,     0xf83f81f6,
    0xf8350347,     0xf83012aa,     0xf8352309,     0xf833330f,
    0xf83653d8,     0xf833435a,     0xf8267129,     0xf82061a6,
    0xf8a78151,     0xf8b80045,     0xf8a012e7,     0xf8be20d4,
    0xf8bc3217,     0xf8bf514e,     0xf8a4402a,     0xf8aa71ba,
    0xf8bc6219,     0xf8e18308,     0xf8ea007c,     0xf8f81325,
    0xf8f523ae,     0xf8e230de,     0xf8f1533f,     0xf8fe4170,
    0xf8ee7157,     0xf8f363a9,     0xf86483c4,     0xf87900ba,
    0xf87011de,     0xf8672130,     0xf8773106,     0xf8635188,
    0xf8604322,     0xf87f73c6,     0xf87660d5,     0xb82081cf,
    0xb83f0233,     0xb82e13e0,     0xb83620b5,     0xb8243373,
    0xb82e5317,     0xb82941ee,     0xb82c72de,     0xb8306118,
    0xb8a782d9,     0xb8be02ee,     0xb8b6123b,     0xb8b621f9,
    0xb8a631fe,     0xb8a7513c,     0xb8b6416f,     0xb8b571df,
    0xb8a76318,     0xb8fd81dd,     0xb8f903f3,     0xb8ee1014,
    0xb8e5229e,     0xb8f9336e,     0xb8e35342,     0xb8e54190,
    0xb8f470eb,     0xb8eb6037,     0xb86e8002,     0xb8780100,
    0xb86710ac,     0xb87d200c,     0xb87a3164,     0xb86e534e,
    0xb878401e,     0xb87b730d,     0xb8626031,     0xce362d71,
    0xce15395a,     0xce738c94,     0xce883450,     0xce688076,
    0xce6486c0,     0xcec08313,     0xce6c8895,     0x04b50226,
    0x043005a6,     0x65d60071,     0x65dc0a03,     0x65ce04af,
    0x04d6b904,     0x04401742,     0x04d08d6e,     0x04dab818,
    0x04d38237,     0x04d19cfe,     0x04d011e7,     0x0497adc4,
    0x045ebe6b,     0x048804da,     0x040a07dd,     0x04811424,
    0x04dcab1b,     0x65c08dac,     0x658d8986,     0x65869799,
    0x65c794b7,     0x65829f84,     0x049dbc33,     0x6582b62f,
    0x6580a020,     0x6581bf67,     0x65cda775,     0x65c1939d,
    0x65eb0caf,     0x65ee3d96,     0x65a45c5b,     0x65e46718,
    0x04515ede,     0x040176dc,     0x042230cc,     0x04bb3231,
    0x047430d1,     0x04e432be,     0x041a3a29,     0x04183f02,
    0x04993a66,     0x040826e9,     0x040a2e78,     0x65c73491,
    0x65c62628,     0x65d82d88,     0x048134f7,
  };
// END  Generated code -- do not edit
