# Runs update-wiki action every day at 20:00 UTC

name: 'Wiki Update'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  wiki:
    if: ${{ github.event_name != 'schedule' || github.repository == 'SAP/SapMachine' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SapMachine Wiki source
        uses: actions/checkout@v4
        with:
          repository: 'SAP/SapMachine.wiki.git'
          ref: 'master'
      - name: Configure git
        run: |
          git config user.name "SapMachine Github Actions Bot"
          git config user.email "sapmachine@sap.com"
          git remote set-url origin https://github.com/SAP/SapMachine.wiki.git
      - name: Update Wiki
        run: |
          pip3 install feedparser
          python3 scripts/update_blogs.py update
          git commit -a -m "Update blogs" || echo "No updates"
      - name: Push changes
        run: git push origin master
        working-directory: .
        shell: bash
