# Runs update-wiki update actions every day at 20:00 UTC

name: 'Wiki Update'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: 'Update Wiki'
        uses: ./.github/actions/update-wiki

