name: 'Wiki-related'

on:
  push:
    branches:
      - sapmachine
  schedule:
    - cron: '0 20 * * *'

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the JDK source'
        uses: actions/checkout@v4
      - name: 'Update Wiki'
        uses: ./.github/actions/update-wiki

