# Runs update-wiki action every day at 20:00 UTC

name: 'Wiki Update'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'SAP/SapMachine.wiki.git'
          ref: 'master'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "SapMachine Github Actions Bot"
          git config user.email "sapmachine@sap.com"
          git remote set-url origin git@github.com:SAP/SapMachine.wiki.git
      - name: Update Wiki
        run: |
          pip3 install feedparser
          python3 scripts/update_blogs.py update
      - run: git push origin master
        working-directory: .
        shell: bash
